// Interface strings and page copy for English.

export const ui = {
  htmlLang: "en",
  languageName: "English",
  switchTo: "Русская версия",
  switchShort: "RU",
  common: {
    skipToContent: "Skip to content",
    home: "home",
    cv: "CV",
    mainNav: "Main",
    footerNav: "Footer",
    mobileNav: "Mobile",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    toggleTheme: "Toggle dark mode",
    todo: "to be added",
    languages: "Languages",
  },
  home: {
    techLabel: "Core technologies",
    viewProjects: "View projects",
    architecture: "Architecture",
    downloadCv: "Download CV",
    contact: "Contact",
    diagramLabel: "Architecture layers: Browser, Next.js, business logic, MongoDB, infrastructure",
    layers: [
      { label: "Browser", sub: "PWA · SSR HTML" },
      { label: "Next.js", sub: "App Router · RSC" },
      { label: "Business logic", sub: "Payload hooks · access" },
      { label: "MongoDB", sub: "collections · indexes" },
      { label: "Infrastructure", sub: "Docker · Nginx · CI/CD" },
    ],
    about: { eyebrow: "About", title: "Systems, not just code" },
    capabilities: {
      eyebrow: "Capabilities",
      title: "From architecture to production",
      description: "Four areas I own on a project — usually all at once.",
    },
    projects: {
      eyebrow: "Selected work",
      title: "Case studies",
      description: "Real systems I designed and built — each with architecture, decisions and trade-offs.",
      architectureLink: "How I approach architecture →",
    },
    contactSection: {
      eyebrow: "Contact",
      title: "Let’s talk about your product",
      description: "Architecture review, technical leadership or building a product from zero — write to me directly.",
    },
  },
  projectsPage: {
    metaTitle: "Projects",
    metaDescription: "Case studies: a translation bureau platform, a multi-locale marketplace, a VR rehabilitation platform and a product launch.",
    eyebrow: "Projects",
    title: "Case studies",
    description:
      "Each case follows the same structure: problem, constraints, architecture, decisions, data model, performance, security, deployment — and what I would do differently.",
  },
  project: {
    readCase: "Read case study",
    role: "Role",
    status: "Status",
    stack: "Technology stack",
    sectionsNav: "Case study sections",
    moreNav: "More case studies",
    allProjects: "All projects",
    nextCase: "Next case:",
    sections: {
      overview: "Overview",
      problem: "Problem",
      constraints: "Constraints",
      architecture: "Architecture",
      decisions: "Technical decisions",
      "data-model": "Data model",
      performance: "Performance",
      security: "Security",
      deployment: "Deployment",
      challenges: "Challenges",
      improvements: "What I would improve",
    },
  },
  architecturePage: {
    metaTitle: "Architecture",
    metaDescription: "Reference architecture behind my products: Next.js + Payload CMS + MongoDB, caching, security and deployment.",
    eyebrow: "Architecture",
    title: "One coherent stack, from browser to server",
    description:
      "The reference architecture I use across products: a single Next.js application with Payload CMS as the application layer, MongoDB for data, and a small, well-understood production setup.",
    system: { title: "System design", description: "A narrow core with well-defined services around it.", core: "Core request path", around: "Around the core" },
    database: { title: "Database architecture", tradeoff: "Trade-off." },
    caching: { title: "Caching", description: "Cheap reads come from decisions made at write time." },
    security: { title: "Security", description: "Defaults that hold on every write path." },
    deployment: { title: "Deployment", description: "Every push to main ends up in production the same way." },
  },
  engineeringPage: {
    metaTitle: "Engineering principles",
    metaDescription:
      "How I make engineering decisions: architecture first, justified complexity, production as part of development, performance as a feature.",
    eyebrow: "Engineering",
    title: "Principles I build by",
    description: "Engineering credibility over decoration. Each principle comes with a place where it shaped a real decision.",
    inPractice: "In practice — ",
    keyPoints: "key points",
  },
  experiencePage: {
    metaTitle: "Experience",
    metaDescription: "Roles and focus areas: software architecture, technical leadership and full-stack product delivery.",
    eyebrow: "Experience",
    title: "Where I’ve been building",
    description: "Architecture, web products, full-stack development, infrastructure and technical leadership.",
    focus: "Focus areas",
    caseStudy: "Case study →",
  },
  contactPage: {
    metaTitle: "Contact",
    metaDescription: "Contact Alexey Grigorovich: email, Telegram and GitHub.",
    eyebrow: "Contact",
    title: "Get in touch",
    description:
      "Open to architecture, CTO and lead developer roles, and to consulting on web products. Email or Telegram is the fastest way to reach me.",
  },
  cvPage: {
    metaTitle: "CV",
    metaDescription: "Printable CV of Alexey Grigorovich — Software Architect, CTO, Lead Developer.",
    printHint: "Printable A4 CV — use “Save as PDF” in the print dialog.",
    printButton: "Download CV (PDF)",
    summary: "Summary",
    skills: "Core skills",
    experience: "Experience",
    projects: "Selected projects",
    architecture: "Architecture",
    infrastructure: "Infrastructure",
    languages: "Languages",
  },
  notFound: {
    metaTitle: "Page not found",
    title: "This route isn’t in the architecture.",
    text: "The page you’re looking for doesn’t exist or has moved.",
    home: "Home",
    projects: "Projects",
  },
};
